# Generated by Django 6.0 on 2025-12-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Layihə adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Layihə açıqlaması')),
                ('technologies', models.TextField(blank=True, null=True, verbose_name='Texnologiyalar')),
                ('site_link', models.URLField(blank=True, null=True, verbose_name='Sayt adresi')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Github linki')),
            ],
            options={
                'verbose_name': 'Layihə',
                'verbose_name_plural': 'Layihələr',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ad, Soyad')),
                ('position', models.CharField(blank=True, max_length=20, null=True, verbose_name='Peşə')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin linki')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Github linki')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram linki')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook linki')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV-ler',
            },
        ),
    ]
