# Generated by Django 6.0 on 2025-12-17 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Şəkil', 'verbose_name_plural': 'Şəkillər'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='image',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myresume.projects', verbose_name='Layihə'),
        ),
        migrations.AlterField(
            model_name='image',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myresume.resume', verbose_name='CV'),
        ),
    ]
