# Generated by Django 5.2.7 on 2025-12-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0003_alter_image_options_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Əsas Şəkil'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
